// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/test/sdk"
)

var (
	_ resource.Resource                = &CustomThingResource{}
	_ resource.ResourceWithConfigure   = &CustomThingResource{}
	_ resource.ResourceWithImportState = &CustomThingResource{}
)

type CustomThingResource struct {
	client *AkeylessClient
}

func NewCustomThingResource() resource.Resource {
	return &CustomThingResource{}
}

type CustomThingModel struct {
	Active types.Bool `tfsdk:"active"`
	Id types.String `tfsdk:"id"`
	Ratio types.Float64 `tfsdk:"ratio"`
	Size types.Int64 `tfsdk:"size"`
	Tags types.Set `tfsdk:"tags"`
}

func (r *CustomThingResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_thing"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Description: "",
				Optional: true,
			},
			"id": schema.StringAttribute{
				Description: "",
				Required: true,
			},
			"ratio": schema.Float64Attribute{
				Description: "",
				Optional: true,
			},
			"size": schema.Int64Attribute{
				Description: "",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "",
				Optional: true,
				Computed: true,
				ElementType: types.StringType{},
			},
		},
	}
}

func (r *CustomThingResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *CustomThingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan CustomThingModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/create")

	// Set active
	if !plan.Active.IsNull() && !plan.Active.IsUnknown() {
		v := plan.Active.ValueBool()
		body.SetActive(&v)
	}

	// Set id
	if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
		v := plan.Id.ValueString()
		body.SetId(&v)
	}

	// Set ratio
	if !plan.Ratio.IsNull() && !plan.Ratio.IsUnknown() {
		v := plan.Ratio.ValueFloat64()
		body.SetRatio(&v)
	}

	// Set size
	if !plan.Size.IsNull() && !plan.Size.IsUnknown() {
		v := plan.Size.ValueInt64()
		body.SetSize(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	tflog.Debug(ctx, "Creating CustomThing")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating CustomThing", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Id.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *CustomThingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state CustomThingModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Id.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *CustomThingResource) readResource(ctx context.Context, id string) (CustomThingModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state CustomThingModel

	body := akeyless_api.NewReadBody("/read")
	body.SetId(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading CustomThing", err.Error())
		return state, diags
	}

	state.Id = types.StringValue(id)
	// TODO: state.Active = ... // no read_mapping defined
	// TODO: state.Id = ... // no read_mapping defined
	// TODO: state.Ratio = ... // no read_mapping defined
	// TODO: state.Size = ... // no read_mapping defined
	// TODO: state.Tags = ... // no read_mapping defined
	_ = result

	return state, diags
}

func (r *CustomThingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan CustomThingModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/update")
	if !plan.Active.IsNull() && !plan.Active.IsUnknown() {
		v := plan.Active.ValueBool()
		body.SetActive(&v)
	}
	if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
		v := plan.Id.ValueString()
		body.SetId(&v)
	}
	if !plan.Ratio.IsNull() && !plan.Ratio.IsUnknown() {
		v := plan.Ratio.ValueFloat64()
		body.SetRatio(&v)
	}
	if !plan.Size.IsNull() && !plan.Size.IsUnknown() {
		v := plan.Size.ValueInt64()
		body.SetSize(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	tflog.Debug(ctx, "Updating CustomThing")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating CustomThing", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *CustomThingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state CustomThingModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete")
	id := state.Id.ValueString()
	body.SetId(&id)

	tflog.Debug(ctx, "Deleting CustomThing", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting CustomThing", err.Error())
		return
	}
}

func (r *CustomThingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
