// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/test/sdk"
)

var (
	_ resource.Resource                = &MetricsResource{}
	_ resource.ResourceWithConfigure   = &MetricsResource{}
	_ resource.ResourceWithImportState = &MetricsResource{}
)

type MetricsResource struct {
	client *AkeylessClient
}

func NewMetricsResource() resource.Resource {
	return &MetricsResource{}
}

type MetricsModel struct {
	Count types.Int64 `tfsdk:"count"`
	Enabled types.Bool `tfsdk:"enabled"`
	Name types.String `tfsdk:"name"`
	Rate types.Float64 `tfsdk:"rate"`
}

func (r *MetricsResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_metrics"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"count": schema.Int64Attribute{
				Description: "",
				Optional: true,
			},
			"enabled": schema.BoolAttribute{
				Description: "",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Required: true,
			},
			"rate": schema.Float64Attribute{
				Description: "",
				Optional: true,
			},
		},
	}
}

func (r *MetricsResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *MetricsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan MetricsModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/create")

	// Set count
	if !plan.Count.IsNull() && !plan.Count.IsUnknown() {
		v := plan.Count.ValueInt64()
		body.SetCount(&v)
	}

	// Set enabled
	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		v := plan.Enabled.ValueBool()
		body.SetEnabled(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set rate
	if !plan.Rate.IsNull() && !plan.Rate.IsUnknown() {
		v := plan.Rate.ValueFloat64()
		body.SetRate(&v)
	}

	tflog.Debug(ctx, "Creating Metrics")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Metrics", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *MetricsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state MetricsModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *MetricsResource) readResource(ctx context.Context, id string) (MetricsModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state MetricsModel

	body := akeyless_api.NewReadBody("/read")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading Metrics", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "m_count"); ok {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			state.Count = types.Int64Value(n)
		}
	}
	if v, ok := GetNestedString(result, "m_enabled"); ok {
		state.Enabled = types.BoolValue(v == "true")
	}
	if v, ok := GetNestedString(result, "m_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "m_rate"); ok {
		if n, err := strconv.ParseFloat(v, 64); err == nil {
			state.Rate = types.Float64Value(n)
		}
	}

	return state, diags
}

func (r *MetricsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError(
		"Update Not Supported",
		"This resource does not support updates. Delete and recreate instead.",
	)
}

func (r *MetricsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state MetricsModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting Metrics", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Metrics", err.Error())
		return
	}
}

func (r *MetricsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
