use crate::spec::ResourceSpec;
use crate::type_map::to_tf_name;

/// Generated acceptance test file for a resource.
#[derive(Debug, Clone)]
pub struct GeneratedTest {
    pub file_name: String,
    pub go_code: String,
}

/// Generate acceptance test scaffolding for a resource.
#[must_use]
pub fn generate_test(resource: &ResourceSpec) -> GeneratedTest {
    let type_name = meimei::to_pascal_case(
        resource
            .resource
            .name
            .strip_prefix("akeyless_")
            .unwrap_or(&resource.resource.name),
    );

    let tf_name = &resource.resource.name;
    let file_name = format!("resource_{}_test.go", to_tf_name(tf_name));

    let id_field = &resource.identity.id_field;

    let mut code = String::new();

    code.push_str(&format!(
        r#"// Code generated by terraform-forge. DO NOT EDIT.

package resources_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAcc{type_name}_basic(t *testing.T) {{
	rName := fmt.Sprintf("tf-test-%s", acctest.RandStringFromCharSet(10, acctest.CharSetAlphaNum))

	resource.Test(t, resource.TestCase{{
		PreCheck:                 func() {{ testAccPreCheck(t) }},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{{
			// Create and Read
			{{
				Config: testAcc{type_name}Config_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("{tf_name}.test", "{id_field}", rName),
				),
			}},
			// ImportState
			{{
				ResourceName:      "{tf_name}.test",
				ImportState:       true,
				ImportStateVerify: true,
"#
    ));

    // Skip sensitive fields in import verify
    let sensitive_fields: Vec<&str> = resource
        .fields
        .iter()
        .filter(|(_, v)| v.sensitive)
        .map(|(k, _)| k.as_str())
        .collect();

    if !sensitive_fields.is_empty() {
        code.push_str("\t\t\t\tImportStateVerifyIgnore: []string{");
        for (i, field) in sensitive_fields.iter().enumerate() {
            if i > 0 {
                code.push_str(", ");
            }
            code.push_str(&format!("\"{}\"", to_tf_name(field)));
        }
        code.push_str("},\n");
    }

    code.push_str(&format!(
        r#"			}},
		}},
	}})
}}

func testAcc{type_name}Config_basic(name string) string {{
	return fmt.Sprintf(`
resource "{tf_name}" "test" {{
  {id_field} = "%s"
"#
    ));

    // Add required fields with placeholder values
    // This is a scaffold — users must fill in real values
    code.push_str("  # TODO: Add required fields\n");

    code.push_str(&format!(
        r#"}}
`, name)
}}
"#
    ));

    GeneratedTest {
        file_name,
        go_code: code,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_basic_test() {
        let toml_str = r#"
[resource]
name = "akeyless_static_secret"
description = "Static secret"
category = "secret"

[crud]
create_endpoint = "/create-secret"
create_schema = "createSecret"
read_endpoint = "/get-secret-value"
read_schema = "getSecretValue"
delete_endpoint = "/delete-item"
delete_schema = "deleteItem"

[identity]
id_field = "name"
force_new_fields = ["name"]

[fields]
value = { sensitive = true }
"#;
        let resource: ResourceSpec = toml::from_str(toml_str).expect("parse");
        let test = generate_test(&resource);
        assert!(test.go_code.contains("TestAccStaticSecret_basic"));
        assert!(test.go_code.contains("ImportStateVerifyIgnore"));
        assert!(test.go_code.contains("\"value\""));
        assert_eq!(test.file_name, "resource_akeyless_static_secret_test.go");
    }
}
